version: '3.8'

services:
  factory-postgres:
    container_name: factory-postgres
    hostname: factory-postgres
    image: postgres:13.0-alpine
    env_file:
      - ./app/.env
    networks:
      - factory-main-net
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    command: -p 5433

  factory-app:
    container_name: factory-app
    hostname: factory-app
    build: 
      context: ./app
      args:
        REPO_PATH: ./
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    environment:
      - "MIGRATIONS=1"
    volumes:
      - ./app:/app
      - ./images:/images
    ports:
      - "0.0.0.0:8006:8006"
    restart: always
    depends_on:
      - factory-postgres
    working_dir: /app
    networks:
      - factory-main-net


volumes:
  postgresql-data:
    driver: local

networks:
  factory-main-net:
    driver: bridge
